name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            preset: default
          - os: windows-latest
            preset: windows-only
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@v4
      - run: cmake --preset ${{ matrix.preset }}
      - run: cmake --build build/default
